// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.
 
package frc.robot;

import com.revrobotics.CANSparkMax;
import com.revrobotics.CANSparkLowLevel.MotorType;

import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.Joystick;
// import frc.robot.commands.*;
// import frc.robot.subsystems.*;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import static frc.robot.Constants.ControllerConstants.OPERATOR_PORT;
import static frc.robot.Constants.IntakeConstants.*;
import static frc.robot.POM_lib.Joysticks.JoystickConstants.LEFT_STICK_Y;
import static frc.robot.POM_lib.Joysticks.JoystickConstants.*;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.Commands.ArcadeDriveCommand;
import frc.robot.Commands.CloseArmCommand;
import frc.robot.Commands.IntakeCommand;
import frc.robot.Commands.OpenArmCommand;
import frc.robot.Commands.ResistGravityCommad;
import frc.robot.POM_lib.Joysticks.PomController;
import frc.robot.POM_lib.Joysticks.PomXboxController;
import frc.robot.Subsystems.ArmSubsystem;
import frc.robot.Subsystems.DriveSubsytems;
import frc.robot.Subsystems.IntakeSubsystem;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 * This class is where the bulk of the robot should be declared.  Since Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in the {@link Robot}
 * periodic methods (other than the scheduler calls).  Instead, the structure of the robot
 * (including subsystems, commands, and button mappings) should be declared here.
 */
public class RobotContainer {

  private static RobotContainer m_robotContainer = new RobotContainer();
  private static DriveSubsytems m_DriveSubsytems = new DriveSubsytems();
  private static ArmSubsystem m_ArmSubsystem = new ArmSubsystem();
  private static IntakeSubsystem m_IntakeSubsystem = new IntakeSubsystem();
// Joysticks

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public PomController controller = new PomXboxController(OPERATOR_PORT);

  
  // A chooser for autonomous commands
  SendableChooser<Command> m_chooser = new SendableChooser<>();
  
  /**
  * The container for the robot.  Contains subsystems, OI devices, and commands.
  */
  private RobotContainer() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
    // Smartdashboard Subsystems

    // SmartDashboard Buttons

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
    // Configure the button bindings
    configureButtonBindings();

    // Configure default commands
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND
      m_DriveSubsytems.setDefaultCommand(new ArcadeDriveCommand(m_DriveSubsytems, () -> controller.getLeftY(), () -> controller.getRightX()));
      m_IntakeSubsystem.setDefaultCommand(new IntakeCommand(m_IntakeSubsystem, 0));
      m_ArmSubsystem.setDefaultCommand(new ResistGravityCommad(m_ArmSubsystem));

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND

    // Configure autonomous sendable chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    SmartDashboard.putData("Auto Mode", m_chooser);
  }

  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  /**
   * Use this method to define your button->command mappings.  Buttons can be created by
   * instantiating a {@link GenericHID} or one of its subclasses ({@link
   * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing it to a
   * {@link edu.wpi.first.wpilibj2.command.button.JoystickButton}.
   */
  private void configureButtonBindings() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
// Create some buttons
        controller.a().whileTrue(new OpenArmCommand(m_ArmSubsystem, OPEN_SPEED));
        controller.b().whileTrue(new CloseArmCommand(m_ArmSubsystem, FOLD_SPEED));
        controller.rightTrigger().whileTrue(new IntakeCommand(m_IntakeSubsystem, INTAKE_SPEED));
        controller.leftTrigger().whileTrue(new IntakeCommand(m_IntakeSubsystem, OUTAKE_SPEED));
                // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
  }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

  /**
   * Use this to pass the autonomous command to the main {@link Robot} class.
   *
   * @return the command to run in autonomous
  */
  public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
    return m_chooser.getSelected();
  }
 
  

}

